/**
 * 补充完整中小学高中必背古诗文
 * 数据来源：教育部统编版语文教材"背诵推荐篇目"
 * - 小学：75篇（1-6年级）
 * - 初中：61篇（7-9年级）
 * - 高中：72篇（含新课标推荐）
 *
 * 用法: bun run scripts/seed-chinese-full.ts
 */
import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

interface TextItem {
  stage: string
  grade: string
  order: number
  title: string
  author?: string
  dynasty?: string
  category: string
  content: string
  annotation?: string
  translation?: string
  wordCount: number
  difficulty: string
  isRequired: boolean
}

const TEXTS: TextItem[] = [
  // ============ 小学（补充至75篇） ============
  // 一年级（补充）
  { stage: '小学', grade: '一年级', order: 4, title: '悯农（其二）', author: '李绅', dynasty: '唐', category: '古诗词',
    content: '锄禾日当午，\n汗滴禾下土。\n谁知盘中餐，\n粒粒皆辛苦。',
    annotation: '悯：怜悯。禾：庄稼。',
    translation: '农民在正午烈日下锄禾，汗水滴入禾苗下的泥土。谁知道盘中的饭食，每一粒都来自辛苦的劳作。',
    wordCount: 20, difficulty: 'A1', isRequired: true },
  { stage: '小学', grade: '一年级', order: 5, title: '古朗月行（节选）', author: '李白', dynasty: '唐', category: '古诗词',
    content: '小时不识月，\n呼作白玉盘。\n又疑瑶台镜，\n飞在青云端。',
    translation: '小时候不认识月亮，把它叫作白玉盘。又怀疑是瑶台的仙镜，飞在青云的顶端。',
    wordCount: 20, difficulty: 'A1', isRequired: true },
  { stage: '小学', grade: '一年级', order: 6, title: '风', author: '李峤', dynasty: '唐', category: '古诗词',
    content: '解落三秋叶，\n能开二月花。\n过江千尺浪，\n入竹万竿斜。',
    translation: '能吹落秋天的树叶，能催开二月的鲜花。吹过江面能掀起千尺巨浪，吹入竹林能让万竿翠竹倾斜。',
    wordCount: 20, difficulty: 'A1', isRequired: true },

  // 二年级（补充）
  { stage: '小学', grade: '二年级', order: 6, title: '悯农（其一）', author: '李绅', dynasty: '唐', category: '古诗词',
    content: '春种一粒粟，\n秋收万颗子。\n四海无闲田，\n农夫犹饿死。',
    annotation: '粟：谷子。',
    translation: '春天播下一粒谷种，秋天收获万颗粮食。四海之内没有空闲的田地，可农民还是会饿死。',
    wordCount: 20, difficulty: 'A1', isRequired: true },
  { stage: '小学', grade: '二年级', order: 7, title: '赠刘景文', author: '苏轼', dynasty: '宋', category: '古诗词',
    content: '荷尽已无擎雨盖，\n菊残犹有傲霜枝。\n一年好景君须记，\n最是橙黄橘绿时。',
    translation: '荷花谢尽已无撑雨的荷叶，菊花枯萎还有傲霜的枝条。一年的好景你一定要记住，正是橙子金黄橘子青绿的时候。',
    wordCount: 28, difficulty: 'A1', isRequired: true },
  { stage: '小学', grade: '二年级', order: 8, title: '夜宿山寺', author: '李白', dynasty: '唐', category: '古诗词',
    content: '危楼高百尺，\n手可摘星辰。\n不敢高声语，\n恐惊天上人。',
    translation: '山上寺院的高楼真高啊，站在上面手都能摘到星辰。不敢大声说话，怕惊动了天上的仙人。',
    wordCount: 20, difficulty: 'A1', isRequired: true },
  { stage: '小学', grade: '二年级', order: 9, title: '敕勒歌', category: '古诗词', dynasty: '北朝民歌',
    content: '敕勒川，阴山下。\n天似穹庐，笼盖四野。\n天苍苍，野茫茫，\n风吹草低见牛羊。',
    annotation: '穹庐：毡帐。见：同"现"。',
    translation: '敕勒川在阴山脚下。天空像巨大的毡帐，笼罩着四面的原野。天蓝蓝的，原野辽阔无边，风吹过草地露出了牛羊。',
    wordCount: 27, difficulty: 'A2', isRequired: true },

  // 三年级（补充）
  { stage: '小学', grade: '三年级', order: 9, title: '赠汪伦', author: '李白', dynasty: '唐', category: '古诗词',
    content: '李白乘舟将欲行，\n忽闻岸上踏歌声。\n桃花潭水深千尺，\n不及汪伦送我情。',
    translation: '李白正乘船要出发，忽然听到岸上传来踏歌的声音。桃花潭的水有千尺深，也比不上汪伦送我的情谊深。',
    wordCount: 28, difficulty: 'A1', isRequired: true },
  { stage: '小学', grade: '三年级', order: 10, title: '望洞庭', author: '刘禹锡', dynasty: '唐', category: '古诗词',
    content: '湖光秋月两相和，\n潭面无风镜未磨。\n遥望洞庭山水翠，\n白银盘里一青螺。',
    translation: '秋月的清辉与湖光相互辉映，潭面无风像未打磨的铜镜。远望洞庭湖的山水一片翠绿，像白银盘里放着一只青螺。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '三年级', order: 11, title: '采莲曲', author: '王昌龄', dynasty: '唐', category: '古诗词',
    content: '荷叶罗裙一色裁，\n芙蓉向脸两边开。\n乱入池中看不见，\n闻歌始觉有人来。',
    translation: '采莲女的罗裙与荷叶同色，荷花向着她的脸庞两边盛开。混入池中分不清人影，听到歌声才发觉有人来。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '三年级', order: 12, title: '忆江南', author: '白居易', dynasty: '唐', category: '古诗词',
    content: '江南好，风景旧曾谙。\n日出江花红胜火，\n春来江水绿如蓝，\n能不忆江南？',
    annotation: '谙：熟悉。',
    translation: '江南的风景好，我以前就很熟悉。日出时江边的花比火还红，春天来了江水绿得像蓝草。怎能不回忆江南？',
    wordCount: 27, difficulty: 'A2', isRequired: true },

  // 四年级（补充）
  { stage: '小学', grade: '四年级', order: 10, title: '暮江吟', author: '白居易', dynasty: '唐', category: '古诗词',
    content: '一道残阳铺水中，\n半江瑟瑟半江红。\n可怜九月初三夜，\n露似真珠月似弓。',
    annotation: '瑟瑟：碧绿色。可怜：可爱。',
    translation: '一道夕阳铺在江面上，半江碧绿半江红。可爱的九月初三的夜晚，露水像珍珠月亮像弯弓。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '四年级', order: 11, title: '出塞', author: '王昌龄', dynasty: '唐', category: '古诗词',
    content: '秦时明月汉时关，\n万里长征人未还。\n但使龙城飞将在，\n不教胡马度阴山。',
    translation: '秦时的明月汉时的关塞，万里征战的将士还未归来。只要有龙城飞将李广在，就不让胡人的战马越过阴山。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '四年级', order: 12, title: '凉州词', author: '王翰', dynasty: '唐', category: '古诗词',
    content: '葡萄美酒夜光杯，\n欲饮琵琶马上催。\n醉卧沙场君莫笑，\n古来征战几人回？',
    translation: '葡萄美酒倒在夜光杯里，正要饮时琵琶声在马上催促。如果醉倒在沙场上请不要笑，自古以来征战有几人能回来？',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '四年级', order: 13, title: '夏日绝句', author: '李清照', dynasty: '宋', category: '古诗词',
    content: '生当作人杰，\n死亦为鬼雄。\n至今思项羽，\n不肯过江东。',
    translation: '活着要做人中豪杰，死了也要做鬼中英雄。至今人们还在思念项羽，他宁死不肯退回江东。',
    wordCount: 20, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '四年级', order: 14, title: '别董大', author: '高适', dynasty: '唐', category: '古诗词',
    content: '千里黄云白日曛，\n北风吹雁雪纷纷。\n莫愁前路无知己，\n天下谁人不识君。',
    translation: '千里黄云遮蔽了白日，北风吹送大雁大雪纷纷落下。不要发愁前路没有知己，天下有谁不认识你呢？',
    wordCount: 28, difficulty: 'A2', isRequired: true },

  // 五年级（补充）
  { stage: '小学', grade: '五年级', order: 13, title: '示儿', author: '陆游', dynasty: '宋', category: '古诗词',
    content: '死去元知万事空，\n但悲不见九州同。\n王师北定中原日，\n家祭无忘告乃翁。',
    translation: '本来就知道人死后万事皆空，只是悲伤看不到国家统一。当宋军收复中原的那天，家祭时别忘了告诉你的父亲。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '五年级', order: 14, title: '题临安邸', author: '林升', dynasty: '宋', category: '古诗词',
    content: '山外青山楼外楼，\n西湖歌舞几时休？\n暖风熏得游人醉，\n直把杭州作汴州。',
    translation: '山外有青山楼外有楼，西湖边的歌舞什么时候才能停止？暖风把游人熏得醉醺醺的，简直把杭州当成了汴州。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '五年级', order: 15, title: '己亥杂诗', author: '龚自珍', dynasty: '清', category: '古诗词',
    content: '九州生气恃风雷，\n万马齐喑究可哀。\n我劝天公重抖擞，\n不拘一格降人才。',
    translation: '中国的生机要依靠风雷般的变革，万马齐喑的局面实在可悲。我劝老天爷重新振作精神，不拘一格地降下人才。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '五年级', order: 16, title: '山居秋暝', author: '王维', dynasty: '唐', category: '古诗词',
    content: '空山新雨后，天气晚来秋。\n明月松间照，清泉石上流。\n竹喧归浣女，莲动下渔舟。\n随意春芳歇，王孙自可留。',
    translation: '空山刚下过一场雨，傍晚的天气有了秋意。明月透过松林洒落，清泉在石头上流淌。竹林喧闹是洗衣女归来，莲叶摇动是渔船下水。任凭春天的芳华消歇，王孙自可留居山中。',
    wordCount: 40, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '五年级', order: 17, title: '长相思', author: '纳兰性德', dynasty: '清', category: '古诗词',
    content: '山一程，水一程，\n身向榆关那畔行，夜深千帐灯。\n风一更，雪一更，\n聒碎乡心梦不成，故园无此声。',
    annotation: '榆关：山海关。聒：吵闹。',
    translation: '翻山越岭跋山涉水，向山海关那边行进，夜深时千万个帐篷里灯火通明。风雪交加一更又一更，吵得思乡的心梦都做不成，故乡可没有这样的声音。',
    wordCount: 36, difficulty: 'A2', isRequired: true },

  // 六年级（补充）
  { stage: '小学', grade: '六年级', order: 16, title: '宿建德江', author: '孟浩然', dynasty: '唐', category: '古诗词',
    content: '移舟泊烟渚，\n日暮客愁新。\n野旷天低树，\n江清月近人。',
    translation: '把船停靠在烟雾迷蒙的小洲旁，夕阳西下惹起旅人新的愁绪。原野空旷天幕低垂似乎与树相接，江水清澈水中的月影仿佛与人亲近。',
    wordCount: 20, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '六年级', order: 17, title: '六月二十七日望湖楼醉书', author: '苏轼', dynasty: '宋', category: '古诗词',
    content: '黑云翻墨未遮山，\n白雨跳珠乱入船。\n卷地风来忽吹散，\n望湖楼下水如天。',
    translation: '乌云像打翻的墨汁还没遮住山，白色的雨点像跳动的珍珠乱纷纷落入船中。一阵卷地风忽然把云雨吹散，望湖楼下水面平静得像天空。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '六年级', order: 18, title: '春日', author: '朱熹', dynasty: '宋', category: '古诗词',
    content: '胜日寻芳泗水滨，\n无边光景一时新。\n等闲识得东风面，\n万紫千红总是春。',
    translation: '在风和日丽的好日子来到泗水河边寻找春色，无边无际的风光焕然一新。随便就能认出东风的面貌，万紫千红都是春天的景色。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '六年级', order: 19, title: '回乡偶书', author: '贺知章', dynasty: '唐', category: '古诗词',
    content: '少小离家老大回，\n乡音无改鬓毛衰。\n儿童相见不相识，\n笑问客从何处来。',
    translation: '年少时离开家乡年老时才回来，乡音没有改变但鬓发已经稀疏。孩子们见了面不认识我，笑着问我从哪里来。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '六年级', order: 20, title: '浪淘沙', author: '刘禹锡', dynasty: '唐', category: '古诗词',
    content: '九曲黄河万里沙，\n浪淘风簸自天涯。\n如今直上银河去，\n同到牵牛织女家。',
    translation: '弯弯曲曲的黄河带着万里黄沙，波浪翻滚风簸着来自天涯。如今我要直上银河去，一同到牛郎织女的家中。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '六年级', order: 21, title: '江南春', author: '杜牧', dynasty: '唐', category: '古诗词',
    content: '千里莺啼绿映红，\n水村山郭酒旗风。\n南朝四百八十寺，\n多少楼台烟雨中。',
    translation: '千里江南莺啼燕语绿映红花，水乡山城酒旗在风中飘扬。南朝的四百八十座寺庙，多少楼台笼罩在蒙蒙烟雨中。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '小学', grade: '六年级', order: 22, title: '书湖阴先生壁', author: '王安石', dynasty: '宋', category: '古诗词',
    content: '茅檐长扫净无苔，\n花木成畦手自栽。\n一水护田将绿绕，\n两山排闼送青来。',
    annotation: '排闼：推门。',
    translation: '茅草房檐下经常打扫干净没有青苔，花木成行都是亲手栽种。一条小溪护卫着农田环绕绿意，两座青山像推门一样送来翠色。',
    wordCount: 28, difficulty: 'A2', isRequired: true },

  // ============ 初中（补充至61篇） ============
  // 七年级（补充）
  { stage: '初中', grade: '七年级', order: 5, title: '峨眉山月歌', author: '李白', dynasty: '唐', category: '古诗词',
    content: '峨眉山月半轮秋，\n影入平羌江水流。\n夜发清溪向三峡，\n思君不见下渝州。',
    translation: '峨眉山上半轮秋月，月影倒映在平羌江水中随波流动。夜里从清溪出发前往三峡，思念你却看不见你，只好顺流而下渝州。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '初中', grade: '七年级', order: 6, title: '江南逢李龟年', author: '杜甫', dynasty: '唐', category: '古诗词',
    content: '岐王宅里寻常见，\n崔九堂前几度闻。\n正是江南好风景，\n落花时节又逢君。',
    translation: '在岐王府里经常见到你，在崔九堂前多次听到你的歌声。正是江南风景最美的时候，落花的时节又遇到了你。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '初中', grade: '七年级', order: 7, title: '行军九日思长安故园', author: '岑参', dynasty: '唐', category: '古诗词',
    content: '强欲登高去，\n无人送酒来。\n遥怜故园菊，\n应傍战场开。',
    translation: '勉强想登高去，却无人送酒来。遥想可怜故园的菊花，应该正开在战场旁边。',
    wordCount: 20, difficulty: 'A2', isRequired: true },
  { stage: '初中', grade: '七年级', order: 8, title: '夜上受降城闻笛', author: '李益', dynasty: '唐', category: '古诗词',
    content: '回乐烽前沙似雪，\n受降城外月如霜。\n不知何处吹芦管，\n一夜征人尽望乡。',
    translation: '回乐烽前的沙地白得像雪，受降城外的月光寒如秋霜。不知何处吹起芦笛，一夜之间戍边的将士都在望乡。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '初中', grade: '七年级', order: 9, title: '秋词（其一）', author: '刘禹锡', dynasty: '唐', category: '古诗词',
    content: '自古逢秋悲寂寥，\n我言秋日胜春朝。\n晴空一鹤排云上，\n便引诗情到碧霄。',
    translation: '自古以来人们逢秋就悲叹寂寥，我却说秋天胜过春天。晴空中一只白鹤冲破云层飞上天空，就把诗情引到了碧蓝的九霄。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '初中', grade: '七年级', order: 10, title: '夜雨寄北', author: '李商隐', dynasty: '唐', category: '古诗词',
    content: '君问归期未有期，\n巴山夜雨涨秋池。\n何当共剪西窗烛，\n却话巴山夜雨时。',
    translation: '你问我归期我说不准，巴山的夜雨涨满了秋天的池塘。何时能一起在西窗下剪烛夜谈，再诉说今夜巴山夜雨的情景。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '初中', grade: '七年级', order: 11, title: '十一月四日风雨大作', author: '陆游', dynasty: '宋', category: '古诗词',
    content: '僵卧孤村不自哀，\n尚思为国戍轮台。\n夜阑卧听风吹雨，\n铁马冰河入梦来。',
    translation: '僵直地躺在孤村里不为自己悲哀，还想着为国守卫边疆。深夜躺着听风吹雨声，铁马冰河的战斗场景进入了梦境。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '初中', grade: '七年级', order: 12, title: '潼关', author: '谭嗣同', dynasty: '清', category: '古诗词',
    content: '终古高云簇此城，\n秋风吹散马蹄声。\n河流大野犹嫌束，\n山入潼关不解平。',
    translation: '自古以来高耸的云团簇拥着这座城，秋风吹散了马蹄声。黄河流过广阔的原野还嫌受束缚，山脉进入潼关后就不肯再平坦。',
    wordCount: 28, difficulty: 'A2', isRequired: true },
  { stage: '初中', grade: '七年级', order: 13, title: '木兰诗（节选）', category: '古诗词', dynasty: '北朝民歌',
    content: '唧唧复唧唧，木兰当户织。\n不闻机杼声，惟闻女叹息。\n问女何所思，问女何所忆。\n女亦无所思，女亦无所忆。\n昨夜见军帖，可汗大点兵。\n军书十二卷，卷卷有爷名。\n阿爷无大儿，木兰无长兄。\n愿为市鞍马，从此替爷征。',
    annotation: '机杼：织布机。军帖：征兵文书。可汗：古代西北少数民族君主的称号。',
    translation: '叹息声一声接一声，木兰对着门在织布。听不到织布机的声音，只听到姑娘的叹息。问她想什么，问她思念什么。她也没想什么，她也没思念什么。昨夜看到征兵文书，可汗在大规模征兵。征兵的名册很多卷，每卷都有父亲的名字。父亲没有大儿子，木兰没有长兄。愿意为此去买鞍马，从此代替父亲出征。',
    wordCount: 80, difficulty: 'B1', isRequired: true },

  // 八年级（补充）
  { stage: '初中', grade: '八年级', order: 8, title: '野望', author: '王绩', dynasty: '唐', category: '古诗词',
    content: '东皋薄暮望，徙倚欲何依。\n树树皆秋色，山山唯落晖。\n牧人驱犊返，猎马带禽归。\n相顾无相识，长歌怀采薇。',
    translation: '傍晚在东皋远望，徘徊着不知该归依何处。每棵树都染上秋色，每座山都沐浴着落日余晖。牧人驱赶着牛犊归来，猎马带着猎物回家。彼此相看互不相识，只能长歌一曲怀念采薇的隐士。',
    wordCount: 40, difficulty: 'B1', isRequired: true },
  { stage: '初中', grade: '八年级', order: 9, title: '黄鹤楼', author: '崔颢', dynasty: '唐', category: '古诗词',
    content: '昔人已乘黄鹤去，此地空余黄鹤楼。\n黄鹤一去不复返，白云千载空悠悠。\n晴川历历汉阳树，芳草萋萋鹦鹉洲。\n日暮乡关何处是？烟波江上使人愁。',
    translation: '昔日的仙人已乘黄鹤离去，这里只留下空空的黄鹤楼。黄鹤一去不再回来，白云千载空自悠悠。晴朗的江边历历可见汉阳的树木，芳草茂盛的鹦鹉洲。日暮时故乡在哪里？江上烟波浩渺令人发愁。',
    wordCount: 56, difficulty: 'B1', isRequired: true },
  { stage: '初中', grade: '八年级', order: 10, title: '使至塞上', author: '王维', dynasty: '唐', category: '古诗词',
    content: '单车欲问边，属国过居延。\n征蓬出汉塞，归雁入胡天。\n大漠孤烟直，长河落日圆。\n萧关逢候骑，都护在燕然。',
    translation: '轻车简从去慰问边关，途经属国居延。像随风飘飞的蓬草一样出了汉塞，像北归的大雁一样飞入胡天的上空。茫茫大漠中一缕孤烟笔直升起，滔滔黄河上落日浑圆。在萧关遇到骑马的侦察兵，告诉我都护正在燕然山。',
    wordCount: 40, difficulty: 'B1', isRequired: true },
  { stage: '初中', grade: '八年级', order: 11, title: '渡荆门送别', author: '李白', dynasty: '唐', category: '古诗词',
    content: '渡远荆门外，来从楚国游。\n山随平野尽，江入大荒流。\n月下飞天镜，云生结海楼。\n仍怜故乡水，万里送行舟。',
    translation: '乘船远行经过荆门外，来到楚地游览。山岭随着平原的展开而消失，长江流入广阔的原野。月亮倒映在水中像飞天的明镜，云霞升起结成海市蜃楼。仍然怜爱故乡的江水，万里相送我的行舟。',
    wordCount: 40, difficulty: 'B1', isRequired: true },
  { stage: '初中', grade: '八年级', order: 12, title: '钱塘湖春行', author: '白居易', dynasty: '唐', category: '古诗词',
    content: '孤山寺北贾亭西，水面初平云脚低。\n几处早莺争暖树，谁家新燕啄春泥。\n乱花渐欲迷人眼，浅草才能没马蹄。\n最爱湖东行不足，绿杨阴里白沙堤。',
    translation: '在孤山寺北贾亭西边，湖水刚与堤岸齐平白云低垂。几只早来的黄莺争抢着向阳的暖树，不知谁家的新燕正在啄取春泥筑巢。纷繁的花朵渐渐要迷住人的眼睛，浅浅的青草刚好能没过马蹄。最喜爱湖东的美景流连忘返，绿色杨树荫下的白沙堤。',
    wordCount: 56, difficulty: 'B1', isRequired: true },
  { stage: '初中', grade: '八年级', order: 13, title: '饮酒（其五）', author: '陶渊明', dynasty: '东晋', category: '古诗词',
    content: '结庐在人境，而无车马喧。\n问君何能尔？心远地自偏。\n采菊东篱下，悠然见南山。\n山气日夕佳，飞鸟相与还。\n此中有真意，欲辨已忘言。',
    translation: '在人间建造居室，却没有车马的喧嚣。问我怎么能做到这样？心地高远自然觉得偏僻。在东篱下采摘菊花，悠然间抬头看见南山。山间的气象傍晚时分更美，飞鸟结伴而归。这其中蕴含着真意，想要辨说却已忘记了言语。',
    wordCount: 50, difficulty: 'B1', isRequired: true },
  { stage: '初中', grade: '八年级', order: 14, title: '雁门太守行', author: '李贺', dynasty: '唐', category: '古诗词',
    content: '黑云压城城欲摧，甲光向日金鳞开。\n角声满天秋色里，塞上燕脂凝夜紫。\n半卷红旗临易水，霜重鼓寒声不起。\n报君黄金台上意，提携玉龙为君死。',
    translation: '黑云压城城墙似乎要崩塌，铠甲在阳光下闪现金鳞般的光芒。号角声响彻秋色满天的天空，边塞上的胭脂色在夜幕中凝成紫色。半卷着红旗逼近易水，霜重鼓寒声音低沉不起。为报答君王黄金台上的厚意，手持玉龙宝剑为您效死。',
    wordCount: 56, difficulty: 'B1', isRequired: true },
  { stage: '初中', grade: '八年级', order: 15, title: '赤壁', author: '杜牧', dynasty: '唐', category: '古诗词',
    content: '折戟沉沙铁未销，自将磨洗认前朝。\n东风不与周郎便，铜雀春深锁二乔。',
    translation: '折断的戟沉埋在沙中铁还没销蚀，自己拿来磨洗后认出是前朝遗物。如果东风不给周郎方便，铜雀台春深时就会锁住二乔。',
    wordCount: 28, difficulty: 'B1', isRequired: true },
  { stage: '初中', grade: '八年级', order: 16, title: '春望', author: '杜甫', dynasty: '唐', category: '古诗词',
    content: '国破山河在，城春草木深。\n感时花溅泪，恨别鸟惊心。\n烽火连三月，家书抵万金。\n白头搔更短，浑欲不胜簪。',
    translation: '国都沦陷山河依旧存在，城池春天来了草木茂密深深。感伤时事花儿也溅出泪水，怨恨离别鸟儿也心惊。战火连续三个月不停，一封家信抵得上万金。白发越搔越短，简直要插不住簪子了。',
    wordCount: 40, difficulty: 'B1', isRequired: true },

  // 九年级（补充）
  { stage: '初中', grade: '九年级', order: 11, title: '行路难（其一）', author: '李白', dynasty: '唐', category: '古诗词',
    content: '金樽清酒斗十千，玉盘珍羞直万钱。\n停杯投箸不能食，拔剑四顾心茫然。\n欲渡黄河冰塞川，将登太行雪满山。\n闲来垂钓碧溪上，忽复乘舟梦日边。\n行路难，行路难，多歧路，今安在？\n长风破浪会有时，直挂云帆济沧海。',
    translation: '金杯中的美酒一斗价值十千，玉盘里的珍羞值万钱。停下酒杯放下筷子不能下咽，拔出宝剑四处张望心中茫然。想渡过黄河冰块堵塞了河道，想登上太行山大雪封满了山路。闲暇时在碧绿的溪边垂钓，忽然又梦见乘船经过太阳旁边。行路难啊行路难，岔路这么多，如今身在何处？总有一天会乘长风破万里浪，挂上云帆横渡沧海。',
    wordCount: 84, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 12, title: '酬乐天扬州初逢席上见赠', author: '刘禹锡', dynasty: '唐', category: '古诗词',
    content: '巴山楚水凄凉地，二十三年弃置身。\n怀旧空吟闻笛赋，到乡翻似烂柯人。\n沉舟侧畔千帆过，病树前头万木春。\n今日听君歌一曲，暂凭杯酒长精神。',
    translation: '在巴山楚水这样凄凉的地方，我被弃置了二十三年。怀念故友空吟着思旧赋，回到故乡倒像那个烂柯的人。沉船旁边有千帆驶过，病树前面万木逢春。今天听你唱了这一曲，暂且凭借这杯酒振奋精神。',
    wordCount: 56, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 13, title: '月夜忆舍弟', author: '杜甫', dynasty: '唐', category: '古诗词',
    content: '戍鼓断人行，边秋一雁声。\n露从今夜白，月是故乡明。\n有弟皆分散，无家问死生。\n寄书长不达，况乃未休兵。',
    translation: '戍楼的鼓声阻断了人行，边塞秋夜传来一声雁鸣。从今夜起进入白露节气，月亮还是故乡的最明亮。有弟弟却都分散各地，没有家可以打听生死。寄出的书信常常不能送达，何况战争还没有停止。',
    wordCount: 40, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 14, title: '长沙过贾谊宅', author: '刘长卿', dynasty: '唐', category: '古诗词',
    content: '三年谪宦此栖迟，万古惟留楚客悲。\n秋草独寻人去后，寒林空见日斜时。\n汉文有道恩犹薄，湘水无情吊岂知。\n寂寂江山摇落处，怜君何事到天涯。',
    translation: '贾谊被贬谪在这里居住了三年，万古以来只留下楚地客子的悲伤。秋草中独自寻找他离去后的踪迹，寒林中空见夕阳西斜。汉文帝虽有道但恩情还是薄，湘水无情又怎能知道我的凭吊。寂静的江山在草木凋零处，可怜你为何事被贬到天涯。',
    wordCount: 56, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 15, title: '左迁至蓝关示侄孙湘', author: '韩愈', dynasty: '唐', category: '古诗词',
    content: '一封朝奏九重天，夕贬潮州路八千。\n欲为圣明除弊事，肯将衰朽惜残年！\n云横秦岭家何在？雪拥蓝关马不前。\n知汝远来应有意，好收吾骨瘴江边。',
    translation: '早上上奏一封奏章到九重天，晚上就被贬到八千里外的潮州。本想为圣明的君主清除弊政，怎肯吝惜衰老的残年！白云横亘秦岭我家在哪里？大雪拥塞蓝关马儿也不前行。知道你远道赶来应该有用意，好在我的尸骨在瘴江边收殓。',
    wordCount: 56, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 16, title: '商山早行', author: '温庭筠', dynasty: '唐', category: '古诗词',
    content: '晨起动征铎，客行悲故乡。\n鸡声茅店月，人迹板桥霜。\n槲叶落山路，枳花明驿墙。\n因思杜陵梦，凫雁满回塘。',
    translation: '早晨起来出行的铃铛已叮当响，客行在外悲伤思念故乡。鸡鸣声里茅草店上方挂着残月，板桥的霜上印着人的足迹。槲树叶落在山路上，枳花明亮地开在驿站墙边。因此想起在杜陵做的梦，梦里野鸭大雁满池塘。',
    wordCount: 40, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 17, title: '咸阳城东楼', author: '许浑', dynasty: '唐', category: '古诗词',
    content: '一上高城万里愁，蒹葭杨柳似汀洲。\n溪云初起日沉阁，山雨欲来风满楼。\n鸟下绿芜秦苑夕，蝉鸣黄叶汉宫秋。\n行人莫问当年事，故国东来渭水流。',
    translation: '一登上高城就涌起万里乡愁，蒹葭和杨柳好像水中的小洲。溪上云气初起太阳已沉入楼阁后，山雨即将来临风满城楼。夕阳下鸟儿飞入秦代苑囿的绿草丛，秋日里蝉在汉代宫殿的黄叶间鸣叫。行人不要问当年的往事，故国东来的渭水仍在流淌。',
    wordCount: 56, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 18, title: '无题', author: '李商隐', dynasty: '唐', category: '古诗词',
    content: '相见时难别亦难，东风无力百花残。\n春蚕到死丝方尽，蜡炬成灰泪始干。\n晓镜但愁云鬓改，夜吟应觉月光寒。\n蓬山此去无多路，青鸟殷勤为探看。',
    translation: '相见很难离别更难，东风无力百花已经凋残。春蚕到死时丝才吐尽，蜡烛成灰时泪才干枯。早晨照镜只愁云鬓改变，夜晚吟诗应觉月光清寒。蓬莱山离此没有多少路，青鸟殷勤地替我探望。',
    wordCount: 56, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 19, title: '行香子·树绕村庄', author: '秦观', dynasty: '宋', category: '古诗词',
    content: '树绕村庄，水满陂塘。倚东风，豪兴徜徉。\n小园几许，收尽春光。\n有桃花红，李花白，菜花黄。\n远远围墙，隐隐茅堂。\n飏青旗，流水桥旁。\n偶然乘兴，步过东冈。\n正莺儿啼，燕儿舞，蝶儿忙。',
    translation: '绿树环绕着村庄，春水涨满了池塘。倚着东风，兴致勃勃地漫步。小小的园子有多大，却收尽了春光。有红色的桃花，白色的李花，黄色的菜花。远远的围墙，隐隐的茅屋。飘扬着青色酒旗，流水旁有座桥。偶然乘着兴致，走过东边的山冈。正是黄莺啼叫，燕子飞舞，蝴蝶忙碌。',
    wordCount: 60, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 20, title: '山坡羊·骊山怀古', author: '张养浩', dynasty: '元', category: '古诗词',
    content: '骊山四顾，阿房一炬，当时奢侈今何处？\n只见草萧疏，水萦纡。\n至今遗恨迷烟树。\n列国周齐秦汉楚，\n赢，都变做了土；\n输，都变做了土。',
    translation: '在骊山四处回望，阿房宫已化为一炬，当时的奢侈如今在哪里？只见野草萧疏，流水萦回。至今遗恨还迷漫在烟树间。列国周齐秦汉楚，赢的，都变成了土；输的，也都变成了土。',
    wordCount: 50, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 21, title: '南乡子·登京口北固亭有怀', author: '辛弃疾', dynasty: '宋', category: '古诗词',
    content: '何处望神州？满眼风光北固楼。\n千古兴亡多少事？悠悠。不尽长江滚滚流。\n年少万兜鍪，坐断东南战未休。\n天下英雄谁敌手？曹刘。生子当如孙仲谋。',
    translation: '从哪里可以望到中原？满眼风光的北固楼上。千古以来多少兴亡事？悠远绵长。不尽的长江滚滚东流。年轻时统帅万千大军，坐镇东南征战不休。天下英雄谁是对手？曹操刘备。生儿子就应当像孙权那样。',
    wordCount: 60, difficulty: 'B2', isRequired: true },
  { stage: '初中', grade: '九年级', order: 22, title: '过零丁洋', author: '文天祥', dynasty: '宋', category: '古诗词',
    content: '辛苦遭逢起一经，干戈寥落四周星。\n山河破碎风飘絮，身世浮沉雨打萍。\n惶恐滩头说惶恐，零丁洋里叹零丁。\n人生自古谁无死？留取丹心照汗青。',
    translation: '辛苦的命运从精通经书开始，在战乱中度过四年。山河破碎像风吹散的柳絮，身世浮沉像雨打的浮萍。在惶恐滩头诉说惶恐，在零丁洋里叹息孤苦零丁。人生自古以来谁无死？留下一颗赤诚的心照耀史册。',
    wordCount: 56, difficulty: 'B2', isRequired: true },

  // ============ 高中（补充至72篇） ============
  // 高一（补充）
  { stage: '高中', grade: '高一', order: 4, title: '短歌行', author: '曹操', dynasty: '汉魏', category: '古诗词',
    content: '对酒当歌，人生几何！\n譬如朝露，去日苦多。\n慨当以慷，忧思难忘。\n何以解忧？唯有杜康。\n青青子衿，悠悠我心。\n但为君故，沉吟至今。\n呦呦鹿鸣，食野之苹。\n我有嘉宾，鼓瑟吹笙。\n明明如月，何时可掇？\n忧从中来，不可断绝。\n越陌度阡，枉用相存。\n契阔谈讌，心念旧恩。\n月明星稀，乌鹊南飞。\n绕树三匝，何枝可依？\n山不厌高，海不厌深。\n周公吐哺，天下归心。',
    annotation: '杜康：代指酒。衿：衣领。掇：拾取。阡陌：田间小路。讌：同"宴"。匝：圈。吐哺：吐出口中食物。',
    translation: '对着美酒应当高歌，人生能有多少岁月！就像早晨的露水，逝去的日子太多。慷慨激昂，忧思难以忘怀。用什么来解忧？只有杜康美酒。青青的是你的衣领，悠悠的是我的思念。只因为你的缘故，让我沉吟至今。鹿群呦呦鸣叫，吃着野外的苹草。我有嘉宾，弹瑟吹笙。明明如月，什么时候可以摘取？忧愁从中而来，不可断绝。穿过纵横的小路，劳驾你来探望。久别重逢设宴畅谈，心中念着旧日恩情。月明星稀，乌鹊向南飞去。绕树飞了三圈，哪根枝可以栖息？山不嫌高，海不嫌深。周公吐哺接待贤才，天下人心归附。',
    wordCount: 160, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高一', order: 5, title: '归园田居（其一）', author: '陶渊明', dynasty: '东晋', category: '古诗词',
    content: '少无适俗韵，性本爱丘山。\n误落尘网中，一去三十年。\n羁鸟恋旧林，池鱼思故渊。\n开荒南野际，守拙归园田。\n方宅十余亩，草屋八九间。\n榆柳荫后檐，桃李罗堂前。\n暧暧远人村，依依墟里烟。\n狗吠深巷中，鸡鸣桑树颠。\n户庭无尘杂，虚室有余闲。\n久在樊笼里，复得返自然。',
    translation: '从小就没有适应世俗的性情，本性就喜爱山林。误落尘世的罗网中，一去就是三十年。笼中的鸟眷恋旧日的森林，池中的鱼思念深潭。在南边原野开垦荒地，安守本分回归田园。住宅有十余亩地，草屋有八九间。榆树柳树遮蔽着后檐，桃树李树排列在堂前。远远的村落依稀可见，村落里的炊烟袅袅升起。狗在深巷中吠叫，鸡在桑树顶端鸣叫。门庭里没有世俗杂事，空寂的居室有闲暇。久困在樊笼里，如今又重返自然。',
    wordCount: 100, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高一', order: 6, title: '梦游天姥吟留别', author: '李白', dynasty: '唐', category: '古诗词',
    content: '海客谈瀛洲，烟涛微茫信难求；\n越人语天姥，云霞明灭或可睹。\n天姥连天向天横，势拔五岳掩赤城。\n天台四万八千丈，对此欲倒东南倾。\n我欲因之梦吴越，一夜飞度镜湖月。\n湖月照我影，送我至剡溪。\n谢公宿处今尚在，渌水荡漾清猿啼。\n脚著谢公屐，身登青云梯。\n半壁见海日，空中闻天鸡。\n千岩万转路不定，迷花倚石忽已暝。\n熊咆龙吟殷岩泉，栗深林兮惊层巅。\n云青青兮欲雨，水澹澹兮生烟。\n列缺霹雳，丘峦崩摧。\n洞天石扉，訇然中开。\n青冥浩荡不见底，日月照耀金银台。\n霓为衣兮风为马，云之君兮纷纷而来下。\n虎鼓瑟兮鸾回车，仙之人兮列如麻。\n忽魂悸以魄动，恍惊起而长嗟。\n惟觉时之枕席，失向来之烟霞。\n世间行乐亦如此，古来万事东流水。\n别君去兮何时还？且放白鹿青崖间。\n须行即骑访名山。\n安能摧眉折腰事权贵，使我不得开心颜！',
    annotation: '瀛洲：仙山。天姥：山名。剡溪：水名。谢公屐：谢灵运特制的木屐。',
    translation: '海上来客谈论瀛洲仙山，烟波渺茫确实难以寻求；越人说起天姥山，云霞明灭或许可以看到。天姥山连着天横亘天际，气势超过五岳压倒赤城山。天台山高四万八千丈，对着天姥山好像要向东南倾倒。我想因此梦游吴越，一夜之间飞越镜湖上的月亮。湖月照着我的身影，送我到剡溪。谢公住宿的地方如今还在，清澈的水波荡漾猿猴啼叫。脚穿谢公特制的木屐，身登直上青云的石阶。在半山腰看见海上日出，在空中听到天鸡鸣叫。千岩万转道路不定，迷恋着花朵倚靠着石头天忽然就黑了。熊咆龙吟震动了岩泉，使深林战栗使层巅惊骇。云层青青好像要下雨，水波荡漾升起烟雾。闪电霹雳，山峦崩塌。仙洞的石门，轰然打开。青天浩荡看不见底，日月照耀着金银台。彩虹为衣风为马，云之君纷纷降临。老虎弹瑟鸾鸟拉车，仙人们排列如麻。忽然魂魄惊动，恍然惊醒发出长叹。只觉得醒来时的枕席，失去了刚才的烟霞。世间行乐也是如此，古来万事都像东流水。与君分别何时才能回来？暂且把白鹿放养在青崖之间。要走时就骑上它访问名山。怎能低眉弯腰侍奉权贵，让我不能开心展颜！',
    wordCount: 300, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高一', order: 7, title: '念奴娇·过洞庭', author: '张孝祥', dynasty: '宋', category: '古诗词',
    content: '洞庭青草，近中秋，更无一点风色。\n玉鉴琼田三万顷，著我扁舟一叶。\n素月分辉，明河共影，表里俱澄澈。\n悠然心会，妙处难与君说。\n应念岭海经年，孤光自照，肝肺皆冰雪。\n短发萧骚襟袖冷，稳泛沧溟空阔。\n尽挹西江，细斟北斗，万象为宾客。\n扣舷独啸，不知今夕何夕！',
    translation: '洞庭湖和青草湖，临近中秋，更没有一点风浪。如玉镜般的湖面三万顷，承载着我这一叶扁舟。明月分出光辉，银河共映倒影，表里都澄澈透明。悠然间心里领会，妙处难以对你诉说。应该想到在岭南沿海经历多年，孤光自照，肝肺都像冰雪一样纯洁。短发稀疏衣袖生寒，平稳地泛舟在空阔的沧溟上。尽情舀取西江之水，用北斗星细细斟酌，万象都是我的宾客。敲着船舷独自长啸，不知今夕是何年！',
    wordCount: 100, difficulty: 'C1', isRequired: true },

  // 高二（补充）
  { stage: '高中', grade: '高二', order: 7, title: '将进酒', author: '李白', dynasty: '唐', category: '古诗词',
    content: '君不见，黄河之水天上来，奔流到海不复回。\n君不见，高堂明镜悲白发，朝如青丝暮成雪。\n人生得意须尽欢，莫使金樽空对月。\n天生我材必有用，千金散尽还复来。\n烹羊宰牛且为乐，会须一饮三百杯。\n岑夫子，丹丘生，将进酒，杯莫停。\n与君歌一曲，请君为我倾耳听。\n钟鼓馔玉不足贵，但愿长醉不复醒。\n古来圣贤皆寂寞，惟有饮者留其名。\n陈王昔时宴平乐，斗酒十千恣欢谑。\n主人何为言少钱，径须沽取对君酌。\n五花马，千金裘，呼儿将出换美酒，与尔同销万古愁。',
    annotation: '岑夫子、丹丘生：李白友人。馔玉：美食。陈王：曹植。',
    translation: '你没看见吗，黄河之水从天而降，奔流到海不再回返。你没看见吗，高堂上的明镜悲叹白发，早晨如青丝傍晚已成白雪。人生得意时应当尽情欢乐，不要让金杯空对明月。天生我材必有大用，千金散尽还会再来。烹羊宰牛暂且作乐，应当一次饮三百杯。岑夫子，丹丘生，请喝酒，杯不要停。我为你们唱一首歌，请你们侧耳倾听。钟鼓美食不足为贵，只愿长醉不再醒。自古以来圣贤都寂寞，只有饮酒者留下美名。陈王曹植从前在平乐观宴饮，一斗酒价值十千尽情欢乐。主人为何说钱少，只管去买酒对君酌饮。五花马，千金裘，呼唤童子拿去换美酒，与你们一同销解万古愁。',
    wordCount: 180, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高二', order: 8, title: '燕歌行并序（节选）', author: '高适', dynasty: '唐', category: '古诗词',
    content: '汉家烟尘在东北，汉将辞家破残贼。\n男儿本自重横行，天子非常赐颜色。\n摐金伐鼓下榆关，旌旆逶迤碣石间。\n校尉羽书飞瀚海，单于猎火照狼山。\n山川萧条极边土，胡骑凭陵杂风雨。\n战士军前半死生，美人帐下犹歌舞。\n大漠穷秋塞草腓，孤城落日斗兵稀。\n身当恩遇常轻敌，力尽关山未解围。\n铁衣远戍辛勤久，玉箸应啼别离后。\n少妇城南欲断肠，征人蓟北空回首。\n边庭飘飖那可度，绝域苍茫无所有。\n杀气三时作阵云，寒声一夜传刁斗。\n相看白刃血纷纷，死节从来岂顾勋。\n君不见沙场征战苦，至今犹忆李将军。',
    translation: '汉朝的战火在东北燃起，汉将辞别家去击破残贼。男儿本来就崇尚横行天下，天子特别给予赏赐。鸣金击鼓进军榆关，旗帜蜿蜒在碣石山间。校尉的紧急文书飞过大漠，单于的猎火照亮狼山。山川萧条到了边塞的尽头，胡骑仗势欺凌夹杂着风雨。战士在阵前死伤过半，将军帐下美人还在歌舞。大漠深秋边塞的草木枯萎，孤城落日之下战斗的士兵稀少。身受皇恩常常轻敌，力尽关山之围仍未解。铁甲远征辛勤已久，妻子的眼泪应该在离别后流尽。城南的少妇肝肠欲断，蓟北的征人空自回首。边庭飘摇哪能度日，绝域苍茫什么都没有。杀气在整天化作阵云，寒夜里传来打更的声音。相看白刃之下鲜血纷纷，为节义而死哪里顾及功勋。你没看见沙场征战的辛苦，至今人们还怀念李将军。',
    wordCount: 220, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高二', order: 9, title: '蜀相', author: '杜甫', dynasty: '唐', category: '古诗词',
    content: '丞相祠堂何处寻？锦官城外柏森森。\n映阶碧草自春色，隔叶黄鹂空好音。\n三顾频烦天下计，两朝开济老臣心。\n出师未捷身先死，长使英雄泪满襟。',
    translation: '丞相的祠堂到哪里去寻找？在锦官城外柏树茂密的地方。映照台阶的碧草独自呈现春色，隔着树叶的黄鹂空有好听的鸣声。三顾茅庐频繁劳烦天下大计，辅佐两朝开创基业是老臣的忠心。出师还没胜利就先死去，长期使英雄们泪满衣襟。',
    wordCount: 56, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高二', order: 10, title: '客至', author: '杜甫', dynasty: '唐', category: '古诗词',
    content: '舍南舍北皆春水，但见群鸥日日来。\n花径不曾缘客扫，蓬门今始为君开。\n盘飧市远无兼味，樽酒家贫只旧醅。\n肯与邻翁相对饮，隔篱呼取尽余杯。',
    translation: '房舍南北都被春水环绕，只见群鸥天天飞来。花间的小路还不曾因为客人而打扫，柴门今天才为您打开。离集市远盘中没有多样的菜肴，家境贫寒只有陈酒。愿意和邻家老翁对饮吗？隔着篱笆呼唤他来喝完剩下的酒。',
    wordCount: 56, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高二', order: 11, title: '登高', author: '杜甫', dynasty: '唐', category: '古诗词',
    content: '风急天高猿啸哀，渚清沙白鸟飞回。\n无边落木萧萧下，不尽长江滚滚来。\n万里悲秋常作客，百年多病独登台。\n艰难苦恨繁霜鬓，潦倒新停浊酒杯。',
    translation: '风急天高猿猴的叫声悲凉，水清沙白鸟儿在盘旋。无边无际的落叶萧萧飘下，不尽的长江滚滚涌来。万里漂泊悲秋常作客他乡，一生多病独自登上高台。艰难困苦使白发增多，潦倒之中新近停了饮酒。',
    wordCount: 56, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高二', order: 12, title: '登岳阳楼', author: '杜甫', dynasty: '唐', category: '古诗词',
    content: '昔闻洞庭水，今上岳阳楼。\n吴楚东南坼，乾坤日夜浮。\n亲朋无一字，老病有孤舟。\n戎马关山北，凭轩涕泗流。',
    translation: '从前就听说洞庭湖的水，今天登上了岳阳楼。吴楚两地在东南分裂，天地日月都在湖中浮动。亲戚朋友没有一个字的消息，年老多病只有一只孤舟。北方关山战马嘶鸣，靠着栏杆泪水横流。',
    wordCount: 40, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高二', order: 13, title: '菩萨蛮·书江西造口壁', author: '辛弃疾', dynasty: '宋', category: '古诗词',
    content: '郁孤台下清江水，中间多少行人泪。\n西北望长安，可怜无数山。\n青山遮不住，毕竟东流去。\n江晚正愁余，山深闻鹧鸪。',
    translation: '郁孤台下的清江水，其中有多少行人的眼泪。向西北眺望长安，可惜被无数山遮挡。青山遮不住江水，毕竟还是向东流去。江边傍晚的景色正使我发愁，深山中听到鹧鸪的叫声。',
    wordCount: 44, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高二', order: 14, title: '虞美人·春花秋月何时了', author: '李煜', dynasty: '南唐', category: '古诗词',
    content: '春花秋月何时了？往事知多少。\n小楼昨夜又东风，故国不堪回首月明中。\n雕栏玉砌应犹在，只是朱颜改。\n问君能有几多愁？恰似一江春水向东流。',
    translation: '春花秋月什么时候才能了结？往事又有多少。小楼昨夜又吹来东风，在明月之中不忍回首故国。雕花栏杆和玉石台阶应该还在，只是红颜已经改变。问你有多少愁？就像一江春水向东流去。',
    wordCount: 56, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高二', order: 15, title: '桂枝香·金陵怀古', author: '王安石', dynasty: '宋', category: '古诗词',
    content: '登临送目，正故国晚秋，天气初肃。\n千里澄江似练，翠峰如簇。\n归帆去棹残阳里，背西风，酒旗斜矗。\n彩舟云淡，星河鹭起，画图难足。\n念往昔，繁华竞逐，叹门外楼头，悲恨相续。\n千古凭高对此，谩嗟荣辱。\n六朝旧事随流水，但寒烟衰草凝绿。\n至今商女，时时犹唱，后庭遗曲。',
    translation: '登高远望，正是故都晚秋，天气开始肃杀。千里清澈的江水像白练，翠绿的山峰像聚集在一起。归来的帆船在夕阳里，背对西风，酒旗斜斜地竖立。彩舟在淡淡的云中，银河中有白鹭飞起，图画也难以描绘。回想往昔，繁华竞逐，叹息门外楼头的荒淫，悲恨相继。千古以来凭高对此，徒然感叹荣辱。六朝旧事随着流水，只有寒烟衰草凝聚着绿意。至今歌女们，还时不时唱着后庭的遗曲。',
    wordCount: 120, difficulty: 'C1', isRequired: true },

  // 高三（补充）
  { stage: '高中', grade: '高三', order: 10, title: '锦瑟', author: '李商隐', dynasty: '唐', category: '古诗词',
    content: '锦瑟无端五十弦，一弦一柱思华年。\n庄生晓梦迷蝴蝶，望帝春心托杜鹃。\n沧海月明珠有泪，蓝田日暖玉生烟。\n此情可待成追忆，只是当时已惘然。',
    translation: '锦瑟为什么有五十根弦，一弦一柱都让人思念青春年华。庄周梦中化为蝴蝶，望帝的春心寄托在杜鹃身上。沧海月明时珍珠像含着泪水，蓝田日暖时美玉升起烟雾。这种情感难道要等到成为追忆时才感到，只是当时就已经惘然了。',
    wordCount: 56, difficulty: 'C2', isRequired: true },
  { stage: '高中', grade: '高三', order: 11, title: '虞姬墓', author: '苏轼', dynasty: '宋', category: '古诗词',
    content: '帐下佳人拭泪痕，门前壮士气如云。\n仓黄不负君王意，只有虞姬与郑君。',
    translation: '帐下的佳人擦去泪痕，门前的壮士气概如云。仓皇之中不负君王心意的，只有虞姬和郑君。',
    wordCount: 28, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高三', order: 12, title: '江城子·乙卯正月二十日夜记梦', author: '苏轼', dynasty: '宋', category: '古诗词',
    content: '十年生死两茫茫，不思量，自难忘。\n千里孤坟，无处话凄凉。\n纵使相逢应不识，尘满面，鬓如霜。\n夜来幽梦忽还乡，小轩窗，正梳妆。\n相顾无言，惟有泪千行。\n料得年年肠断处，明月夜，短松冈。',
    translation: '十年生死两茫茫，不去思量，也自然难忘。千里之外的孤坟，无处诉说凄凉。纵使相逢你应该也不认识我了，我满面风尘，两鬓如霜。夜里忽然做了一个梦回到家乡，小轩窗前，你正在梳妆。相看无言，只有千行泪水。料想年年断肠的地方，就在那明月之夜，短松冈上。',
    wordCount: 70, difficulty: 'C2', isRequired: true },
  { stage: '高中', grade: '高三', order: 13, title: '声声慢', author: '李清照', dynasty: '宋', category: '古诗词',
    content: '寻寻觅觅，冷冷清清，凄凄惨惨戚戚。\n乍暖还寒时候，最难将息。\n三杯两盏淡酒，怎敌他、晚来风急！\n雁过也，正伤心，却是旧时相识。\n满地黄花堆积，憔悴损，如今有谁堪摘？\n守着窗儿，独自怎生得黑！\n梧桐更兼细雨，到黄昏、点点滴滴。\n这次第，怎一个愁字了得！',
    translation: '寻寻找找，冷冷清清，凄凄惨惨悲悲戚戚。乍暖还寒的时候，最难调养休息。三杯两盏淡酒，怎么抵挡得住晚来风急！大雁飞过，正在伤心，却是旧时相识。满地黄花堆积，憔悴枯损，如今有谁值得去摘？守着窗户，独自怎么熬到天黑！梧桐更兼细雨，到黄昏时点点滴滴。这种种情景，怎一个愁字能了得！',
    wordCount: 97, difficulty: 'C2', isRequired: true },
  { stage: '高中', grade: '高三', order: 14, title: '书愤', author: '陆游', dynasty: '宋', category: '古诗词',
    content: '早岁那知世事艰，中原北望气如山。\n楼船夜雪瓜洲渡，铁马秋风大散关。\n塞上长城空自许，镜中衰鬓已先斑。\n出师一表真名世，千载谁堪伯仲间！',
    translation: '早年哪里知道世事的艰难，北望中原意气如山。楼船夜雪中渡过瓜洲，铁马秋风中驰骋大散关。空自期许为塞上长城，镜中衰老的鬓发已经先斑白。一篇出师表真是名传后世，千年来谁能与之匹敌！',
    wordCount: 56, difficulty: 'C2', isRequired: true },
  { stage: '高中', grade: '高三', order: 15, title: '临安春雨初霁', author: '陆游', dynasty: '宋', category: '古诗词',
    content: '世味年来薄似纱，谁令骑马客京华。\n小楼一夜听春雨，深巷明朝卖杏花。\n矮纸斜行闲作草，晴窗细乳戏分茶。\n素衣莫起风尘叹，犹及清明可到家。',
    translation: '近年来人情世态薄得像纱，谁让我骑马客居京城。在小楼上一夜听着春雨声，明早深巷里就会有人卖杏花。在短纸上斜着行书闲写草书，在晴窗下细品着分茶。白衣不要感叹风尘，还来得及清明节回家。',
    wordCount: 56, difficulty: 'C2', isRequired: true },
  { stage: '高中', grade: '高三', order: 16, title: '念奴娇·登建康赏心亭呈史致道留守', author: '辛弃疾', dynasty: '宋', category: '古诗词',
    content: '我来吊古，上危亭，赢得闲愁千斛。\n虎踞龙蟠何处是？只有兴亡满目。\n柳外斜阳，水边归鸟，陇上吹乔木。\n片帆西去，一声谁喷霜竹？\n却忆安石风流，东山岁晚，泪落哀筝曲。\n儿辈功名都付与，长日惟消棋局。\n宝镜难寻，碧云将暮，谁劝杯中绿？\n江头风怒，朝来波浪翻屋。',
    translation: '我来凭吊古迹，登上高亭，赢得了千斛闲愁。虎踞龙蟢的形势在哪里？满眼只有兴亡。柳外的斜阳，水边的归鸟，陇上吹过的乔木风。一片帆向西驶去，是谁吹响了霜竹？却回忆谢安的风流，晚年隐居东山，听到哀筝曲落泪。儿辈的功名都交付了，整日只以下棋消遣。宝镜难以寻觅，碧云将暮，谁劝杯中的绿酒？江头风急，早来的波浪翻过屋顶。',
    wordCount: 100, difficulty: 'C2', isRequired: true },
  { stage: '高中', grade: '高三', order: 17, title: '菩萨蛮·大柏地', author: '毛泽东', dynasty: '近现代', category: '古诗词',
    content: '赤橙黄绿青蓝紫，谁持彩练当空舞？\n雨后复斜阳，关山阵阵苍。\n当年鏖战急，弹洞前村壁。\n装点此关山，今朝更好看。',
    translation: '赤橙黄绿青蓝紫，是谁拿着彩练在空中飞舞？雨后又是斜阳，关山一片苍翠。当年激战正酣，子弹打穿了前村的墙壁。装点这关山，今朝更加好看。',
    wordCount: 40, difficulty: 'C1', isRequired: true },
  { stage: '高中', grade: '高三', order: 18, title: '沁园春·长沙', author: '毛泽东', dynasty: '近现代', category: '古诗词',
    content: '独立寒秋，湘江北去，橘子洲头。\n看万山红遍，层林尽染；\n漫江碧透，百舸争流。\n鹰击长空，鱼翔浅底，万类霜天竞自由。\n怅寥廓，问苍茫大地，谁主沉浮？\n携来百侣曾游，忆往昔峥嵘岁月稠。\n恰同学少年，风华正茂；\n书生意气，挥斥方遒。\n指点江山，激扬文字，粪土当年万户侯。\n曾记否，到中流击水，浪遏飞舟？',
    translation: '深秋时节，我独自站在橘子洲头，湘江向北流去。看万山都红了，层层树林都被染红；满江清澈见底，百舸争相行驶。雄鹰搏击长空，鱼儿在浅水底翔游，万物在霜天之下竞相自由。面对广阔的宇宙惆怅，问苍茫大地，谁来主宰沉浮？曾经携百位同伴来游，回忆往昔峥嵘岁月。恰是同学少年，风华正茂；书生意气，挥斥方遒。指点江山，激扬文字，把当年的万户侯视为粪土。曾记否，到江中流击水，波浪阻止了飞舟？',
    wordCount: 140, difficulty: 'C1', isRequired: true },
]

async function main() {
  console.log('📚 补充必背古诗文...')
  let id = 1000 // 从1000开始避免与已有ID冲突
  let added = 0
  for (const t of TEXTS) {
    await db.chineseText.upsert({
      where: { id },
      update: {},
      create: { id, ...t },
    })
    console.log(`  [${id}] ${t.stage}·${t.grade} - ${t.dynasty ? t.dynasty + '·' : ''}${t.author || ''}《${t.title}》(${t.category}, ${t.wordCount}字)`)
    id++
    added++
  }
  console.log(`\n✅ 新增 ${added} 篇`)

  const counts = await db.chineseText.groupBy({ by: ['stage', 'category'], _count: true, orderBy: { stage: 'asc' } })
  console.log('\n📊 补充后统计:')
  for (const c of counts) console.log(`  ${c.stage}·${c.category}: ${c._count}篇`)
  const total = await db.chineseText.count()
  console.log(`  总计: ${total}篇`)

  await db.$disconnect()
}

main().catch(e => { console.error(e); process.exit(1) }).finally(() => db.$disconnect())
